project:
  type: website
  output-dir: docs

website:
  title: "Chris Lake"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: posts/index.qmd
        text: Analysis
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



